
obj-$(CONFIG_MPDCCP_SCHED_CPF) += mpdccp_sched_cpf.o
mpdccp_sched_cpf-y := sched_cpf.o

obj-$(CONFIG_MPDCCP_SCHED_HANDOVER) += mpdccp_sched_handover.o
mpdccp_sched_handover-y := sched_handover.o

obj-$(CONFIG_MPDCCP_SCHED_ACPF) += mpdccp_sched_acpf.o
mpdccp_sched_acpf-y := sched_acpf.o

