# SPDX-License-Identifier: GPL-2.0

# MPDCCP scheduler modules
obj-$(CONFIG_MPDCCP_SCHED_SRTT) += mpdccp_sched_srtt.o
mpdccp_sched_srtt-y := sched_srtt.o

obj-$(CONFIG_MPDCCP_SCHED_ROUNDROBIN) += mpdccp_sched_rr.o
mpdccp_sched_rr-y := sched_rr.o

obj-$(CONFIG_MPDCCP_SCHED_REDUNDANT) += mpdccp_sched_redundant.o
mpdccp_sched_redundant-y := sched_redundant.o

obj-$(CONFIG_MPDCCP_SCHED_OTIAS) += mpdccp_sched_otias.o
mpdccp_sched_otias-y := sched_otias.o
